---
title: "owner-analysis"
format: html
author: Melissa Griffore, Bernardo Costa
---

```{r}
library(readr)
library(dplyr)
library(ggplot2)
library(tidyr)
```

```{r}
lobster_abundance <- read_csv("~/bernardo_melissa/data/Lobster_Abundance_All_Years_20220829.csv")
```

```{r}
lobster_abundance <- lobster_abundance %>% 
    mutate(SIZE_MM = na_if(SIZE_MM, -99999))
```

```{r}
not_napl <- lobster_abundance %>% 
    filter(SITE != "NAPL")
```

```{r}
aque_70mm <- lobster_abundance %>% 
    filter(SITE == "AQUE" & SIZE_MM >= 70)
```
#visualize data
#lobster carapace length
```{r}
ggplot(data = lobster_abundance, aes(x = SIZE_MM)) +
    geom_histogram() +
    facet_wrap(~SITE)
```
#group by site and year
```{r}
lobsters_summarize <- lobster_abundance %>% 
  group_by(SITE, YEAR) %>% 
  summarize(COUNT = n())
```
#plot data

```{r}
# line plot
ggplot(data = lobsters_summarize, aes(x = YEAR, y = COUNT)) +
  geom_line(aes(color = SITE)) 

# line and point plot
fig<-ggplot(data = lobsters_summarize, aes(x = YEAR, y = COUNT)) +
  geom_point(aes(color = SITE)) +
  geom_line(aes(color = SITE)) + geom_point()
```

```{r}
ggsave("plot/lobster_plot.jpg",fig)
```

